# Generated by Django 5.1.1 on 2024-10-25 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('URL', models.URLField()),
                ('app_details', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppScreen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='app_screens/')),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.app')),
            ],
            options={
                'unique_together': {('name', 'App')},
            },
        ),
    ]
