# Generated by Django 5.1.1 on 2024-10-03 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.app')),
                ('users', models.ManyToManyField(related_name='users', to='users.appusers')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('status', models.CharField(choices=[('DFT', 'Draft'), ('UAP', 'Under Approval'), ('AP', 'Approved'), ('RUN', 'Running'), ('PAU', 'Paused'), ('CMT', 'Complete')], max_length=3)),
                ('projectType', models.CharField(choices=[('QUZ', 'Quiz'), ('SRV', 'Survey')], max_length=3)),
                ('orderQuestion', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.app')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='quizzes.audience')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions')),
                ('question_type', models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('NOPE', 'Numeric Open Ended'), ('OPE', 'Open Ended')], max_length=50)),
                ('orderMultiple', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.project')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choiceText', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='multiple')),
                ('is_correct', models.BooleanField(default=False)),
                ('count', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.appusers')),
                ('audience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.audience')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.multiplechoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.questions')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
