# Generated by Django 5.1.1 on 2024-10-27 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DFT', 'Draft'), ('UAP', 'Under Approval'), ('AP', 'Approved'), ('RUN', 'Running'), ('PAU', 'Paused'), ('CMT', 'Complete')], max_length=3)),
                ('projectType', models.CharField(choices=[('QUZ', 'Quiz'), ('SRV', 'Survey')], max_length=3)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_app', to='company.app')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='quizzes.audience')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.appscreen')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions')),
                ('question_type', models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('NOPE', 'Numeric Open Ended'), ('OPE', 'Open Ended')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=5)),
                ('order', models.IntegerField(blank=True)),
                ('color', models.CharField(default='#111111', max_length=7)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.project')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choiceText', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='multiple')),
                ('is_correct', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#111111', max_length=7)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.questions')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSurveyTaskResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='quizzes.questions')),
                ('selected_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.multiplechoice')),
            ],
        ),
    ]
