# Generated by Django 5.1.1 on 2024-10-03 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audience',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.app'),
        ),
        migrations.AddField(
            model_name='audience',
            name='users',
            field=models.ManyToManyField(related_name='users', to='users.appusers'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.multiplechoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='quizzes.audience'),
        ),
        migrations.AddField(
            model_name='questions',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.project'),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.questions'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.questions'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'question')},
        ),
    ]
