# Generated by Django 5.1.1 on 2024-09-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_multiple_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_correct',
        ),
    ]
