# Generated by Django 5.1.1 on 2024-09-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CNT', 'Contestant'), ('OWN', 'Owner'), ('MNG', 'Manager')], max_length=3),
        ),
    ]
